version: "3.8"

services:

  apache:
    container_name: apache
    build: ./docker/apache
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs

  php5:
    container_name: php5
    build: ./docker/php5
    volumes:
      - ./src:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs

  php8:
    container_name: php8
    build: ./docker/php8
    volumes:
      - ./src/newdashboard/:/usr/local/apache2/htdocs/newdashboard
    working_dir: /usr/local/apache2/htdocs/newdashboard

  db:
    container_name: mariadb
    build: ./docker/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
  #    volumes:
  #      - ./docker/mariadb/database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1